theme: minima
title: Reem Aboutaleb
description: A personal portfolio highlighting my work in biomedical engineering, combining research, machine learning, clinical insight, and real-world problem solving through data-driven projects.

